[package]
name = "bropages"
version = "1.0.0"
authors = ["pjmp"]
edition = "2018"
keywords = ["bro", "bropages", "client", "tldr", "cheatsheet"]
categories = ["command-line-utilities", "command-line-interface"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/pjmp/bropages"
repository = "https://github.com/pjmp/bropages"
description = """
Highly readable supplement to man pages.
Shows simple, concise examples for commands.
"""

[dependencies]
attohttpc = {version = "0.16.1", default-features = false, features = ["json", "tls"]}
bat = {version = "0.17.1", default-features = false, features = ["paging", "regex-onig"]}
clap = {version = "2.33.3", default-features = false, features = ["color", "suggestions"] }
serde = {version = "1.0.123", features = ["derive"] }

[[bin]]
path = "src/main.rs"
name = "bro"

[profile.release]
opt-level = 3
lto = true
panic = 'abort'
