[package]
name = "bropages"
version = "0.1.1"
authors = ["pjmp"]
edition = "2018"
keywords = ["cli"]
categories = ["Command line utilities"]
license = "MIT"
homepage = "https://github.com/pjmp/bropages"
repository = "https://github.com/pjmp/bropages"
description = """
Highly readable supplement to man pages.
Shows simple, concise examples for commands.
"""

[dependencies]
reqwest = {version = "0.10.3", default-features = false, features = ["json"]}
tokio = {version = "0.2.13", features = ["macros"] }
serde = {version = "1.0.48", features = ["derive"] }
syntect = {version = "3.3.0", default-features = false, features = ["parsing", "assets", "dump-load"]}
clap = {version = "2.33.0", features = ["default"] }

[[bin]]
path = "src/main.rs"
name = "bro"
